apiVersion: v1
kind: Secret
metadata:
  name: google-auth-secrets
  namespace: corp-apps
type: Opaque
data:
  client-id: ODM3MDMxMTc1MDkwLXNtdTgybzIzYmdodWVqNGFkb3A1bmUwZm1tN2g5YzdmLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  client-secret: R09DU1BYLThLZW82MG5IU3A5QWFYcS0wUDBNT2JqSGJOS3o=
  auth-secret: c29tZXRoaW5nUmFOZDBt