#
# Traefik Forward Auth Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  namespace: corp-apps
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: thomseddon/traefik-forward-auth:2
        name: traefik-forward-auth
        ports:
        - containerPort: 4181
          protocol: TCP
        env:
        - name: DOMAIN
          value: "kirbyware.io"
           # Mark added
        - name: COOKIE_DOMAIN
          value: "kirbyware.io"
        # - name: COOKIE_DOMAIN
        #   value: "kirbyware.io"
        # - name: AUTH_HOST
        #   value: "auth.kirbyware.io"
        # - name: DEFAULT_ACTION
        #   value: "auth"
        # - name: DEFAULT_PROVIDER
        #   value: "google"
        # - name: LIFETIME
        #   value: "2592000" # 30 days
        # - name: LOG_LEVEL
        #   value: "trace" 
        # - name: LOG_FORMAT
        #   value: "text"
        # - name: WHITELIST
        #   value: "mark@kirbyware.com,mark@kirbyware.io"
        # - name: URL_PATH
        #   value: "/_oauth"
        # INSECURE_COOKIE is required unless using https entrypoint
        - name: INSECURE_COOKIE
          value: "true"
        - name: PROVIDERS_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-auth-secrets
              key: client-id
        - name: PROVIDERS_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-auth-secrets
              key: client-secret
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: google-auth-secrets
              key: auth-secret

---
#
# Auth Service
#
apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
  namespace: corp-apps
  labels:
    app: traefik-forward-auth
spec:
  type: ClusterIP
  selector:
    app: traefik-forward-auth
  ports:
  - name: auth-http
    port: 4181
    targetPort: 4181
---
#
# Auth Middleware
#
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
  namespace: corp-apps
spec:
  forwardAuth:
    address: http://traefik-forward-auth.corp-apps.svc.cluster.local:4181
    authResponseHeaders:
      - X-Forwarded-User
---
apiVersion: v1
kind: Secret
metadata:
  name: google-auth-secrets
  namespace: corp-apps
type: Opaque
data:
  client-id: ODM3MDMxMTc1MDkwLXNtdTgybzIzYmdodWVqNGFkb3A1bmUwZm1tN2g5YzdmLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  client-secret: R09DU1BYLThLZW82MG5IU3A5QWFYcS0wUDBNT2JqSGJOS3o=
  auth-secret: c29tZXRoaW5nUmFOZDBt