kubectl drain lkw-node07 --ignore-daemonsets --delete-emptydir-data
kubectl drain lkw-node06 --ignore-daemonsets --delete-emptydir-data
kubectl drain lkw-node05 --ignore-daemonsets --delete-emptydir-data
kubectl drain lkw-node04 --ignore-daemonsets --delete-emptydir-data
kubectl drain lkw-node03 --ignore-daemonsets --delete-emptydir-data
kubectl drain lkw-node02 --ignore-daemonsets --delete-emptydir-data
kubectl drain lkw-node02 --ignore-daemonsets --delete-emptydir-data
kubectl drain lkw-node01 --ignore-daemonsets --delete-emptydir-data
kubectl drain lkw-node00 --ignore-daemonsets --delete-emptydir-data
kubectl drain lkw-ctl00 --ignore-daemonsets --delete-emptydir-data
