kubectl uncordon lkw-ctl00 
kubectl uncordon lkw-node00
kubectl uncordon lkw-node01
kubectl uncordon lkw-node02
kubectl uncordon lkw-node03
kubectl uncordon lkw-node04
kubectl uncordon lkw-node05
kubectl uncordon lkw-node06
kubectl uncordon lkw-node07
