version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Wrangler CLI
          command: npm install -g @cloudflare/wrangler
      - run:
          name: Authenticate with Cloudflare
          command: echo $CF_API_TOKEN | wrangler config
      - run:
          name: Deploy to Cloudflare Pages
          command: |
              cd ./monorepo/projects/goldstar-academy/site
              wrangler publish

workflows:
  version: 2
  build_and_deploy_workflow:
    jobs:
      - build_and_deploy:
          filters:
            paths:
              only:
                - monorepo/projects/goldstar-academy/site/**