# Create a default IngressClass for Traefik
ingressClass:
  enabled: true
  isDefaultClass: false

  additionalArguments:
  - "--providers.kubernetesingress.ingressclass=traefik"
  - "--ping"

ingressRoute:
  dashboard:
    enabled: true

# Configure providers
#
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true

# Options for the main traefik service, where the entrypoints traffic comes
# from.
service:
  enabled: true
  single: true
  type: LoadBalancer
  annotations: {} 
    - service.beta.kubernetes.io/vultr-loadbalancer-protocol: "tcp"

  # spec:
  #   externalTrafficPolicy: Local
  #   ipFamilies:
  #     - IPv4
  #   ipFamilyPolicy: SingleStack

tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard-kirbyware-io-production-tls
