apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-local-kirbyware-com-production
  namespace: traefik
spec:
  secretName: wildcard-local-kirbyware-com-production-tls
  dnsNames:
    - "local.kirbyware.com"
    - "*.local.kirbyware.com"
  issuerRef:
    name: cloudflare-production
    kind: Issuer