apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-kirbyware-com-production
  namespace: traefik
spec:
  secretName: wildcard-kirbyware-com-production-tls
  dnsNames:
    - "kirbyware.com"
    - "*.kirbyware.com"
  issuerRef:
    name: cloudflare-production
    kind: Issuer