apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-kirbyware-com-production
  namespace: traefik
spec:
  secretName: test-kirbyware-com-production-tls
  dnsNames:
    - "test.kirbyware.com"
  issuerRef:
    name: cloudflare-production
    kind: Issuer