# Create a default IngressClass for Traefik
ingressClass:
  enabled: true
  isDefaultClass: false

  additionalArguments:
  - "--providers.kubernetesingress.ingressclass=traefik"
  - "--ping"

ingressRoute:
  dashboard:
    enabled: true

# Configure providers
#
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true

# Options for the main traefik service, where the entrypoints traffic comes
# from.
service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  spec:
    externalTrafficPolicy: Cluster
    loadBalancerIP: 10.200.10.1 # this should be an IP in the MetalLB range
  loadBalancerSourceRanges: []
  externalIPs: []

tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard-local-kirbyware-com-production-tls
