apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-kirbyware-io-production
  namespace: traefik
spec:
  secretName: wildcard-kirbyware-io-production-tls
  dnsNames:
    - "kirbyware.io"
    - "*.kirbyware.io"
  issuerRef:
    name: cloudflare-production
    kind: Issuer