apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-kirbyware-io-staging
  namespace: traefik
spec:
  secretName: wildcard-kirbyware-io-staging-tls
  dnsNames:
    - "kirbyware.io"
    - "*.kirbyware.io"
  issuerRef:
    name: cloudflare-staging
    kind: Issuer