#ENC[AES256_GCM,data:pjLj9oZtt50NIuQ5mxL/aTU=,iv:9RssoAPMPlgboes6fZfafTRV1N088Ax27PCAN5q1GHI=,tag:tUV4D0TxBKMOO53q6Z5Qaw==,type:comment]
#ENC[AES256_GCM,data:Z/yAa7PRbc9E4Zn7ji3Oz9xmetJJMxBC6A==,iv:SsyPe+ZphctX/V2kptTCzqdCzCowEoxw9Pk+lU6oScM=,tag:Z1QlO7yNLwWJGC3nP5NKQA==,type:comment]
#ENC[AES256_GCM,data:jj+6+cna10K+w1iL01+XofO/6nXuJ7+bDqdMIAVBNQiV,iv:/cuqPpPMiUzMZIdnMSeRAnpHd3RoMtCkmRhFg5/rJlI=,tag:nVIR39Xzh3YW4z1EPB9Rcg==,type:comment]
#ENC[AES256_GCM,data:ToAi4zk5zApdw5HAWyacw7uBCm8WH86XejNmy/f62UphSg==,iv:8UWc/NuxnoHAsAhzMSqmQXVGbNGtD0wMy4woKa3ulAA=,tag:1Ok7hyefyqmfhXFUv0RMsg==,type:comment]
apiVersion: ENC[AES256_GCM,data:hYM=,iv:3YMfALpMftBDbftlr7XZFWIv4BLhAyiowaIz3QBFhTo=,tag:C+igEhUMTgZs/GpvJmkJeg==,type:str]
kind: ENC[AES256_GCM,data:90mKr8rA,iv:DpQ6+yTeJEa1aWVj4Lh+rcoD48O9WnSkLP6zrUH3VfY=,tag:speS1AUQCLrWo1Px91Qgtg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:44eIG6vj8HFkbxQIpqYNAWMIMtA=,iv:iBOXcTjbIBd7tcjsB7f78Ot8Thw2OnQ5z8Bn0sNQaus=,tag:gSCwCpDXstpYpfJyHIr8sw==,type:str]
    namespace: ENC[AES256_GCM,data:iWrMlck=,iv:/22BbcPg9FYD4YFbN7UyECmtfoqbADMK15HBdVoYHdA=,tag:hOdgti3tjedBXrPoSnDy/A==,type:str]
data:
    #ENC[AES256_GCM,data:aTbEYp9oMUTMqfkW69VRYg==,iv:l80n36uvgEX/FXINpWJAUAVT7/O5CUC7ojaDjy4d3gw=,tag:zY9pSAaDULwOWOZiEeKHrQ==,type:comment]
    masterkey: ENC[AES256_GCM,data:VUMf2ctKddme5EwjCB988nyQb35VJwAq,iv:GRSdE0zYbhEP9C+yWK1qMakGpILVOWBM8ZsBdkePpVw=,tag:UiJCi3ix0qSnVxmE5t+JxA==,type:str]
    #ENC[AES256_GCM,data:C58dIPv9zIE=,iv:ivRv47HB6dviuVDWHtzgg23+od/syfILE8bi9LRcr/o=,tag:qMpb4o00WT5oPK8PcTaZQg==,type:comment]
    appid: ENC[AES256_GCM,data:iX4lHf0/5yRKIFPZ,iv:gIctr3oqW4iLrK8WDrJwiiOfY41u00VZSSBWZxwBVDI=,tag:0xOH4q1Jbi+rKnFKIQbTxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15qvp6zlk4cxapra3xv3lx7vqyc6e8e3gnv277ly4qxmzr6dgvadsdpsm0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbkFvc3RoQmYva0VLcXBa
            UTN5TEMzcHVuOU9RTnIvbXVGZTM1Y2E0Y1JVCkxrT0FhUWNMQW9aVnlkcEk3b1ov
            UkxlN2c0UVkyZXA4bzNoSjBrTlhuL0UKLS0tIDVzaHhGYnNDbGFHY1VndkY1a3pL
            QVMzT1RyRTM3SEJZdXZFcXF4WnhDSmsK/QkhFvGdMoGcTWU4fwhQ3Lu8sqaPPPPo
            QgLTOX96Y3ljZSIPCMp8nb9gBMMkwkyQGJScJlvZy7u939TJ9hn17Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T19:55:37Z"
    mac: ENC[AES256_GCM,data:EHjtNLrobbfow5vcKYcN1TqZSi5U1KecyIhL7063XzMPPPwn4wPjyrxk/u9o5RKBgt7NbOad+zghueGaNcdZ7SkV8mFbScY2prqRWlxud2wMNtjUz8e/hASzGitW5FJ1bCvnR9ERfLr0Pxc0qPcq4sHKW8DNAEQyOwcmD4Xisko=,iv:Ad2QuztZGVYpr2a1kzeVjh+gAV0o71BllAAio4M23w4=,tag:WXotLsqoEcqc9XDAul5Dhg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
