# encrypeted with 
# cd prod/homelan/9-parse/
# cypher parse-server-secrets.yaml --encrypted-regex='^.*(masterkey|appid).*$' 
# 
# to decrypt 
# cd prod/homelan/9-parse/
# use: sops -d parse-server-secrets.enc.yaml > parse-server-secrets.yaml
#####
apiVersion: v1
kind: Secret
metadata:
    name: parse-server-secrets
    namespace: parse
data:
    #0gZxQss8GGysgaDY
    masterkey: ENC[AES256_GCM,data:j3gC5Xnt/vSuCuaBCcDuD+wfXTQXoQZs,iv:KqzLlUky67VBGTKcXfCPAIUxBZAOM+9H61/xxbtpy6k=,tag:YMDsOLM4+ppDTiMaTevr5w==,type:str]
    #jXX2j8Xk
    appid: ENC[AES256_GCM,data:iW4BoNRyJ/xIcHyB,iv:eaARoWwoxC3Pg5Mqz8HyL9KJ1hNVppi8mC2kvtrA668=,tag:4naaMBXiiciG0j+n8lgE/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15qvp6zlk4cxapra3xv3lx7vqyc6e8e3gnv277ly4qxmzr6dgvadsdpsm0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NHFsMi9UTnRETGY1YUpY
            R0R3L2hqT01wQkNsVmUyRGcxanRsUVlkQTNRCkdKczZISzl1Q1lnb3RvUWZZSFNj
            RjR4MVdJbU1Yb2VrMHZsS1I2NkxSbW8KLS0tIDZ0ZXZ4K3FPTXdYVTN0UXBONExa
            KzlpSXFpRURRUVh6RFg4V1ovd29tZ3MKX+TYRKOXTyUWlptPpCumoUmHhOuKUOso
            5JtzNTXog15XbUSuvZjylsVVFceAqpeBmF4Uflrdek9cTM+ziVpV5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T20:02:40Z"
    mac: ENC[AES256_GCM,data:ItcUKOBKmpZuEzu2yY7vWH/6gLMt1t7Eb+If81hxQENeGhaco20iWxdL15WnJzmQN1d5rX+Cq8FBT9G644gBj/FgiyDVQ+9ugcaaUz6WAiLcGWcqkTEugptzBhVK9G182RUilmzWF0pjfifeeVwLPm0iif1dj7vDsBuDMNymogk=,iv:9rpjBnDkZz/Hng19lkVJAb+IKvvGSSWplU/46ob6KTE=,tag:5z8wMbho2HuM65sed0PAdw==,type:str]
    pgp: []
    encrypted_regex: ^.*(masterkey|appid).*$
    version: 3.7.3
