apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-kirbyware-com-staging
  namespace: traefik
spec:
  secretName: wildcard-kirbyware-com-staging-tls
  dnsNames:
    - "kirbyware.com"
    - "*.kirbyware.com"
  issuerRef:
    name: cloudflare-staging
    kind: Issuer