# Create a default IngressClass for Traefik
ingressClass:
  enabled: true
  isDefaultClass: false

  additionalArguments:
  - "--providers.kubernetesingress.ingressclass=traefik"
  - "--ping"

ingressRoute:
  dashboard:
    enabled: true  

# Configure providers
#
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true

# ports:
#   web:
#     forwardedHeaders:
#       trustedIPs: 
#       - 0.0.0.0/0
#     proxyProtocol:
#       trustedIPs: 
#       - 0.0.0.0/0
#   websecure:
#     forwardedHeaders:
#       trustedIPs: 
#       - 0.0.0.0/0
#     proxyProtocol:
#       trustedIPs: 
#       - 0.0.0.0/0

# Options for the main traefik service, where the entrypoints traffic comes
# from.
service:
  enabled: true
  single: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  spec:
    externalTrafficPolicy: Cluster
    loadBalancerIP: 10.200.10.1 # this should be an IP in the MetalLB range
  loadBalancerSourceRanges: []
  externalIPs: []

tlsStore:
  default:
    certificates:
    - secretName: test-kirbyware-com-production-tls
    - secretName: wildcard-kirbyware-com-production-tls
    defaultCertificate:                                                       
      secretName: wildcard-kirbyware-com-production-tls

tlsOptions: {}