
#################################################################
# Global configuration overrides.
#
# These overrides will affect all helm charts (ie. applications)
# that are listed below and are 'enabled'.
#################################################################
global:
  readinessImage: onap/oom/readiness:3.0.1
  pullPolicy: Always
  clusterName: cluster.local 
  addTestingComponents: false
  centralizedLoggingEnabled: false
  persistence:
    storageClass: openebs-rwx
    mountPath: /onap/data
    storageclassProvisioner: openebs.io/nfsrwx
  # override default resource limit flavor for all charts
  flavor: unlimited
  debugEnabled: false
  ingress:
    enabled: false
    enable_all: false
    virtualhost:
      baseurl: "simpleonap.kirbyware.com"
      preaddr: ""
      postaddr: ""
  serviceMesh:
    enabled: false
    tls: false
    engine: "istio" # valid value: istio or linkerd

  authorizationPolicies:
    enabled: false

  metrics:
    enabled: false
    custom_resources: false

  aafEnabled: false
  msbEnabled: false
  offlineDeploymentBuild: false
  tlsEnabled: false
  centralizedLoggingEnabled: false

aaf:
  enabled: false
  aaf-sms:
    cps:
      # you must always set the same values as value set in cps.enabled
      enabled: false
aai:
  enabled: true
  global:
    cassandra:
      replicas: 1
  aai-cassandra:
    replicaCount: 1

cassandra:
  enabled: true
  replicaCount: 2

cds:
  enabled: false
clamp:
  enabled: false
cli:
  enabled: false
consul:
  enabled: false
contrib:
  enabled: false
cps:
  enabled: false
dcaegen2-services:
  enabled: false
holmes:
  enabled: false
dmaap:
  enabled: true
  message-router:
    enabled: true
  dmaap-bc:
    enabled: true
  dmaap-dr-prov:
    enabled: true
  dmaap-dr-node:
    enabled: true
  message-router:
    enabled: false
  dmaap-bc:
    enabled: false
  dmaap-dr-prov:
    enabled: false
  dmaap-dr-node:
    enabled: false

log:
  enabled: false
sniro-emulator:
  enabled: false
oof:
  enabled: false
mariadb-galera:
  enabled: true
msb:
  enabled: false
multicloud:
  enabled: false
nbi:
  enabled: false
policy:
  enabled: false
pomba:
  enabled: false
portal:
  enabled: false
robot:
  enabled: false
  config:

sdc:
  enabled: true
  sdc-be:
    config:
      javaOptions: "-Xdebug -agentlib:jdwp=transport=dt_socket,address=4000,server=y,suspend=n -Xmx512m -Xms256m"
  sdc-fe:
    resources:
      small:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 10m
          memory: 500Mi
  sdc-cs:
    config:
      maxHeapSize: "512M"
      heapNewSize: "256M"
sdnc:
  enabled: false
  replicaCount: 1
  mysql:
    replicaCount: 1

so:
  enabled: false
  replicaCount: 1
  liveness:
    enabled: false

  # so server configuration
  config:
    # openstack configuration
    openStackUserName: "$OPENSTACK_USER_NAME"
    openStackRegion: "$OPENSTACK_REGION"
    openStackKeyStoneUrl: "$OPENSTACK_KEYSTONE_URL"
    openStackServiceTenantName: "$OPENSTACK_TENANT_NAME"
    openStackEncryptedPasswordHere: "$OPENSTACK_ENCRYPTED_PASSWORD"
  
  strimzi:
    enabled: false
    # Kafka replication & disk storage should be dimensioned
    # according to each given system use case.
    replicaCount: 3
    persistence:
      kafka:
        size: 10Gi
      zookeeper:
        size: 1Gi
    # Strimzi kafka bridge is an optional http api towards
    # kafka provided by https://strimzi.io/docs/bridge/latest/
    strimzi-kafka-bridge:
      enabled: false
uui:
  enabled: false
vfc:
  enabled: false
vnfsdk:
  enabled: false
modeling:
  enabled: false
platform:
  enabled: false
a1policymanagement:
  enabled: false
cert-wrapper:
  enabled: true
repository-wrapper:
  enabled: true
roles-wrapper:
  enabled: true