apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
 name: cstor-disk-pool
 namespace: openebs
spec:
 pools:
   - nodeSelector:
       kubernetes.io/hostname: "kw07-node-641962ff076b"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-32ed588af04305df476199e9eddad6b6"
     poolConfig:
       dataRaidGroupType: "stripe"
